//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_TeamPlayers11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlyaerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Total_Match_Played { get; set; }
        public string Contact_Number { get; set; }
        public string Email { get; set; }
        public string Date_Of_Birth { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<float> Weight { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
